# Generated by Django 2.1.5 on 2023-01-28 13:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('rango', '0002_auto_20230128_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
