# Generated by Django 2.1.5 on 2023-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('rango', '0004_auto_20230128_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
